/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.cwdbillingdisbursement;

import com.lentrix.cwdbillingdisbursement.models.Billing;
import com.lentrix.cwdbillingdisbursement.models.OtherCharges;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hawkman
 */
public class OtherChargesForm extends javax.swing.JDialog {
    private Billing billing;
    /**
     * Creates new form OtherChargesForm
     */
    public OtherChargesForm(java.awt.Frame parent, boolean modal, Billing billing) {
        super(parent, modal);
        
        initComponents();
        this.billing = billing;
        
        try {
            if(this.billing.getOtherCharges()==null) {
                this.billing.setOtherCharges(
                        new OtherCharges(-1, billing, 0.0f, 0.0f, 0.0f, 0.0f,
                                0.0f,0.0f,"",0.0f,"",0.0f,""));
            }
        }catch(SQLException ex) {
            Base.error(ex.getMessage(), parent);
            ex.printStackTrace();
        }
        
        refreshForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code// TODO add your handling code here:. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OtherCharges");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Other Charges");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            OtherCharges oth = this.billing.getOtherCharges();
            oth.setNiCharge(Base.floatify(jTable1.getValueAt(0, 1)));
            oth.setReconCharge(Base.floatify(jTable1.getValueAt(1, 1)));
            oth.setRelocCharge(Base.floatify(jTable1.getValueAt(2, 1)));
            oth.setPcaCharge(Base.floatify(jTable1.getValueAt(3, 1)));
            oth.setMeterSaleCharge(Base.floatify(jTable1.getValueAt(4, 1)));
            oth.setOther1Charge(Base.floatify(jTable1.getValueAt(6, 1)));
            oth.setOther2Charge(Base.floatify(jTable1.getValueAt(7, 1)));
            oth.setOther3Charge(Base.floatify(jTable1.getValueAt(8, 1)));
            oth.setOther1Name(String.valueOf(jTable1.getValueAt(6, 1)));
            oth.setOther2Name(String.valueOf(jTable1.getValueAt(7, 1)));
            oth.setOther3Name(String.valueOf(jTable1.getValueAt(8, 1)));
            
            this.dispose();
            
        }catch(SQLException ex) {
            Base.error(ex.getMessage(), this);
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void refreshForm() {
        try {
            OtherCharges oth = this.billing.getOtherCharges();
            Object content[][] = {
                {"N.I.", oth.getNiCharge()==0?null:oth.getNiCharge()},
                {"Recon", oth.getReconCharge()==0?null:oth.getReconCharge()},
                {"Reloc", oth.getRelocCharge()==0?null:oth.getRelocCharge()},
                {"PCA", oth.getPcaCharge()==0?null:oth.getPcaCharge()},
                {"Meter Sale", oth.getMeterSaleCharge()==0?null:oth.getMeterSaleCharge()},
                {"Others", null},
                {oth.getOther1Name()==""?null:oth.getOther1Name(),oth.getOther1Charge()==0?null:oth.getOther1Charge()},
                {oth.getOther2Name()==""?null:oth.getOther2Name(),oth.getOther2Charge()==0?null:oth.getOther2Charge()},
                {oth.getOther3Name()==""?null:oth.getOther3Name(),oth.getOther3Charge()==0?null:oth.getOther3Charge()},
                {"Total", oth.getTotal()==0?null:oth.getTotal()}
            };
            
            String header[] = {"Account", "Amount"};
            DefaultTableModel model = new DefaultTableModel(content, header) {

                @Override
                public void setValueAt(Object aValue, int row, int column) {
                    super.setValueAt(aValue, row, column);
                    if(row<9) {
                        super.setValueAt(this.getTotal(), 9, 1);
                    }
                }

                @Override
                public boolean isCellEditable(int row, int column) {
                    return (column==1 && row!=5 && row<9) || (row>5 && row<9);
                }

                private float getTotal() {
                    float total = 0f;
                    for(int i=0; i<this.getRowCount()-1; i++) {
                        try {
                            total += Float.parseFloat(String.valueOf(this.getValueAt(i, 1)));
                        }catch(NumberFormatException ex) {

                        }
                    }
                    return total;
                }

            };
            jTable1.setModel(model);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(Base.getRightRender());
        }catch(SQLException ex) {
            Base.error(ex.getMessage(), this);
            ex.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
